name: Deploy to Amazon EC2

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3  
      - name: Docker Login
        run:
          docker login ${{ secrets.LOGIN}}
      - name: Docker Push
        run: |
          ${{ secrets.RUN}}  
      - name: Deploy in EC2
        run: |
          ${{ secrets.DEPLOY}}



   
